name: TheBlackSheep
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22754
title: 'TheBlackSheep Photography - dedicated to Fetish, Erotic and Fine Art photography'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfb'
    - '#003b4b'
    - '#636363'
    - '#bfbfbf'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
